# Generated by Django 6.0.1 on 2026-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscompetence',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pfmp',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='pfmp',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
