# Generated by Django 6.0.1 on 2026-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_souscompetence_code_alter_pfmp_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critereevaluation',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
