# Generated by Django 6.0.1 on 2026-02-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_critereevaluation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecontrat',
            name='indicateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indicateurperformance', verbose_name='Indicateur de performance'),
        ),
    ]
