# Generated by Django 6.0.1 on 2026-02-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lignecontrat_indicateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossieratelier',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
