# Generated by Django 6.0.1 on 2026-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dossieratelier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='visible_eleves',
            field=models.BooleanField(default=True, verbose_name='Visible par les élèves'),
        ),
    ]
