# Generated by Django 6.0.1 on 2026-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_connexioneleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='commentaire_sortie',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='raison_sortie',
            field=models.CharField(blank=True, choices=[('cap_mention', 'CAP obtenu avec mention'), ('cap_sans_mention', 'CAP obtenu sans mention'), ('bac_pro_mention', 'Bac Pro obtenu avec mention'), ('bac_pro_sans_mention', 'Bac Pro obtenu sans mention'), ('echec_cap', 'Échoué au CAP'), ('echec_bac_pro', 'Échoué au Bac Pro'), ('poursuite_bac_pro', 'Poursuite en Bac Pro'), ('poursuite_bts', 'Poursuite en BTS'), ('poursuite_autre', "Autre poursuite d'études"), ('travail_formation', 'Travaille en lien avec sa formation'), ('travail_hors_formation', 'Travaille hors de sa formation'), ('apprentissage', 'Apprentissage / Alternance'), ('sans_emploi', 'Sans emploi'), ('reorientation_interne', "Réorienté dans l'établissement"), ('reorientation_externe', 'Réorienté dans un autre établissement'), ('retour_pays', "Retour dans son pays d'origine"), ('exclusion', "Exclu de l'établissement"), ('decrocheur', 'Décrocheur (abandon)'), ('deces', 'Décès'), ('raison_inconnue', 'Raison inconnue')], default='', max_length=50),
        ),
    ]
