# Generated by Django 6.0.1 on 2026-03-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_commentaire_sortie_granular_raison'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_revision_creees', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_revision', to='core.theme')),
            ],
            options={
                'verbose_name': 'Fiche de révision',
                'verbose_name_plural': 'Fiches de révision',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='CarteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='core.ficherevision')),
            ],
            options={
                'verbose_name': 'Carte de révision',
                'verbose_name_plural': 'Cartes de révision',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_limite', models.DateTimeField()),
                ('melange_questions', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms', to='core.classe')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms_crees', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qcms', to='core.theme')),
            ],
            options={
                'verbose_name': 'QCM',
                'verbose_name_plural': 'QCM',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='QuestionQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('choix_a', models.CharField(max_length=300)),
                ('choix_b', models.CharField(max_length=300)),
                ('choix_c', models.CharField(blank=True, max_length=300)),
                ('choix_d', models.CharField(blank=True, max_length=300)),
                ('bonne_reponse', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.qcm')),
            ],
            options={
                'verbose_name': 'Question QCM',
                'verbose_name_plural': 'Questions QCM',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SessionQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponses', models.JSONField(default=dict)),
                ('note_sur_20', models.FloatField(blank=True, null=True)),
                ('nb_bonnes_reponses', models.IntegerField(default=0)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('termine', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_qcm', to='core.profilutilisateur')),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.qcm')),
            ],
            options={
                'verbose_name': 'Session QCM',
                'verbose_name_plural': 'Sessions QCM',
                'unique_together': {('qcm', 'eleve')},
            },
        ),
    ]
