# Generated by Django 6.0.1 on 2026-03-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ficherevision_carterevision_qcm_questionqcm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(help_text='Ex : 2024-2025', max_length=9, verbose_name='Année scolaire')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_eleves', to='core.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_classes', to='core.profilutilisateur', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Historique classe',
                'verbose_name_plural': 'Historiques classes',
                'ordering': ['eleve', 'date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SuiviPFMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_jours_effectues', models.PositiveIntegerField(default=0, verbose_name='Jours effectués')),
                ('nb_jours_manques_justifies', models.PositiveIntegerField(default=0, verbose_name='Absences justifiées (j)')),
                ('nb_jours_manques_injustifies', models.PositiveIntegerField(default=0, verbose_name='Absences injustifiées (j)')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_pfmp', to='core.profilutilisateur', verbose_name='Élève')),
                ('pfmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='core.pfmp', verbose_name='PFMP')),
            ],
            options={
                'verbose_name': 'Suivi PFMP élève',
                'verbose_name_plural': 'Suivis PFMP élèves',
                'ordering': ['pfmp', 'eleve__user__last_name'],
                'unique_together': {('pfmp', 'eleve')},
            },
        ),
    ]
