# Generated by Django 6.0.3 on 2026-03-04 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historiqueclasse_suivipfmp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modes_operatoires', to='core.atelier', verbose_name='Atelier')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_operatoires', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modes_operatoires', to='core.theme', verbose_name='Thème')),
            ],
            options={
                'verbose_name': 'Mode opératoire',
                'verbose_name_plural': 'Modes opératoires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneModeOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('phase', models.CharField(help_text='Ex : "Approvisionnement des matériaux"', max_length=200, verbose_name='Phase')),
                ('schema_image', models.ImageField(blank=True, null=True, upload_to='modes_operatoires/schemas/', verbose_name='Schéma / image')),
                ('operations', models.TextField(verbose_name='Opérations détaillées')),
                ('materiels', models.TextField(verbose_name='Matériels et outils')),
                ('controle', models.TextField(verbose_name='Points de contrôle')),
                ('risques_sante', models.TextField(verbose_name='Risques santé et prévention')),
                ('risques_environnement', models.TextField(verbose_name='Risques environnement et prévention')),
                ('mode_operatoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.modeoperatoire', verbose_name='Mode opératoire')),
            ],
            options={
                'verbose_name': 'Ligne mode opératoire',
                'verbose_name_plural': 'Lignes mode opératoire',
                'ordering': ['ordre'],
            },
        ),
    ]
