# Generated by Django 6.0.3 on 2026-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_modeoperatoire_visible_eleves'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueclasse',
            name='redoublement',
            field=models.BooleanField(default=False, verbose_name='Redoublement'),
        ),
    ]
