# Generated by Django 6.0.3 on 2026-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_redoublement_historiqueClasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='classe',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Garçon'), ('F', 'Fille')], max_length=1, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='theme',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='themes', to='core.classe'),
        ),
    ]
