# Generated by Django 6.0.3 on 2026-03-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_theme_classe_profilutilisateur_sexe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='formation_choisie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='type_sortie',
            field=models.CharField(blank=True, choices=[('', 'Non renseigné'), ('poursuite_etudes', "Poursuite d'études"), ('reorientation_interne', 'Réorientation interne'), ('reorientation_externe', 'Réorientation externe'), ('passage_classe_sup', 'Passage en classe supérieure'), ('autre', 'Autre')], default='', max_length=30),
        ),
    ]
