# Generated by Django 6.0.3 on 2026-03-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profilutilisateur_formation_choisie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherevision',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_revision', to='core.dossier'),
        ),
    ]
