# Generated by Django 6.0.3 on 2026-03-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ficherevision_dossier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficherevision',
            name='theme',
        ),
        migrations.AlterField(
            model_name='ficherevision',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_revision', to='core.dossier'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='raison_sortie',
            field=models.CharField(blank=True, choices=[('cap_mention', 'Obtention CAP (avec mention)'), ('cap_sans_mention', 'Obtention CAP (sans mention)'), ('bac_pro_mention', 'Obtention Bac Pro (avec mention)'), ('bac_pro_sans_mention', 'Obtention Bac Pro (sans mention)'), ('poursuite_bac_pro', 'Poursuite en Bac Pro (Post-Formation)'), ('poursuite_bts', 'Poursuite en BTS (Post-Formation)'), ('poursuite_autre', "Autre poursuite d'études (Post-Formation)"), ('travail_formation', 'Travaille dans le BTP (Post-Formation)'), ('travail_hors_formation', 'Travaille hors BTP (Post-Formation)'), ('apprentissage', 'Apprentissage / Alternance (Post-Formation)'), ('orientation_afb', 'Orientation en 1ère AFB (Reste au lycée)'), ('reorientation_interne', 'Réorientation interne (Autre filière)'), ('reorientation_externe', 'Réorientation externe (Autre lycée/CFA)'), ('echec_cap', 'Échec au CAP'), ('echec_bac_pro', 'Échec au Bac Pro'), ('decrocheur', "Décrocheur (abandon en cours d'année)"), ('sans_emploi', 'Sans emploi (Sorti du système)'), ('exclusion', 'Exclusion définitive'), ('retour_pays', "Retour dans le pays d'origine"), ('deces', 'Décès'), ('raison_inconnue', 'Raison inconnue')], default='', max_length=50),
        ),
    ]
