# Generated by Django 6.0.3 on 2026-03-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_ficherevision_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='parcours',
            field=models.CharField(blank=True, choices=[('ORGO', 'ORGO'), ('AFB', 'AFB')], max_length=10, null=True),
        ),
    ]
