# Generated by Django 6.0.3 on 2026-03-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_profilutilisateur_parcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communications/')),
                ('annotation_data', models.TextField(blank=True, help_text="JSON ou SVG de l'annotation côté client", null=True)),
                ('texte', models.TextField(blank=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='nouveau', max_length=30)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.profilutilisateur')),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
