# Generated by Django 6.0.3 on 2026-03-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('image_annotee', models.ImageField(blank=True, null=True, upload_to='messages/annotees/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(limit_choices_to={'type_utilisateur': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='core.profilutilisateur')),
                ('professeur', models.ForeignKey(limit_choices_to={'type_utilisateur': 'professeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='core.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Message élève',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ReponseProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.messageeleve')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_envoyees', to='core.profilutilisateur')),
            ],
            options={
                'verbose_name': 'Réponse professeur',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.DeleteModel(
            name='Communication',
        ),
    ]
