# Generated by Django 6.0.3 on 2026-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reset_evaluations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationligne',
            name='note',
            field=models.CharField(choices=[('NE', 'Non évalué'), ('0', '0 - Insuffisant'), ('1', '1 - Fragile'), ('2', '2 - Satisfaisant'), ('3', '3 - Très satisfaisant')], default='NE', max_length=2, verbose_name='Note'),
        ),
    ]
