# Generated by Django 6.0.3 on 2026-04-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_atelier_to_fichecontrat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pfmp',
            options={'ordering': ['date_debut', 'titre'], 'verbose_name': 'PFMP', 'verbose_name_plural': 'PFMP'},
        ),
        migrations.AddField(
            model_name='pfmp',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='pfmp', to='core.classe', verbose_name='Classes concernées'),
        ),
        migrations.AlterField(
            model_name='pfmp',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfmp_old', to='core.classe', verbose_name='Classe (ancien)'),
        ),
    ]
