# Generated by Django 6.0.3 on 2026-04-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_pfmp_copy_classe_to_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfmp',
            name='classe',
        ),
    ]
