# Generated by Django 6.0.3 on 2026-04-06 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pfmp_remove_old_classe_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('type_evaluation', models.CharField(choices=[('formative', 'Formative'), ('sommative', 'Sommative'), ('certificative', 'Certificative')], default='formative', max_length=20, verbose_name="Type d'évaluation")),
                ('unite_evaluation', models.CharField(blank=True, default='', max_length=200, verbose_name="Unité d'évaluation")),
                ('activites_professionnelles', models.TextField(blank=True, default='', verbose_name='Activités professionnelles')),
                ('description_situation', models.TextField(blank=True, default='', verbose_name='Description de la situation professionnelle')),
                ('observation_environnement', models.TextField(blank=True, default='', verbose_name="Observation de l'environnement de travail")),
                ('problematique', models.TextField(blank=True, default='', verbose_name='Problématique')),
                ('validee_par_prof', models.BooleanField(default=False, verbose_name='Validée par le professeur')),
                ('commentaire_prof', models.TextField(blank=True, default='', verbose_name='Commentaire du professeur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ordre', models.IntegerField(default=0)),
                ('competences', models.ManyToManyField(blank=True, related_name='fiches_portfolio', to='core.competenceprofessionnelle', verbose_name='Compétences évaluées')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_portfolio_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('pfmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_portfolio', to='core.pfmp', verbose_name='PFMP associée')),
            ],
            options={
                'verbose_name': 'Fiche portfolio',
                'verbose_name_plural': 'Fiches portfolio',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='portfolio/photos/', verbose_name='Photo / Document')),
                ('legende', models.CharField(blank=True, default='', max_length=200, verbose_name='Légende')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.ficheportfolio', verbose_name='Fiche')),
            ],
            options={
                'verbose_name': 'Photo portfolio',
                'verbose_name_plural': 'Photos portfolio',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='core.profilutilisateur', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['eleve__user__last_name', 'eleve__user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='ficheportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='core.portfolio', verbose_name='Portfolio'),
        ),
    ]
