# Generated by Django 6.0.3 on 2026-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoportfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/photos/', verbose_name='Photo / Document'),
        ),
    ]
