# Generated by Django 6.0.3 on 2026-04-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_photo_portfolio_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheportfolio',
            name='consigne_entreprise',
            field=models.TextField(blank=True, default='', verbose_name="Consigne de l'entreprise"),
        ),
        migrations.AddField(
            model_name='ficheportfolio',
            name='materiels_disponibles',
            field=models.TextField(blank=True, default='', verbose_name='Je dispose (matériels, matériaux)'),
        ),
        migrations.AddField(
            model_name='ficheportfolio',
            name='risques_epi',
            field=models.TextField(blank=True, default='', verbose_name='Identifier les risques et déduire les EPI'),
        ),
        migrations.AddField(
            model_name='ficheportfolio',
            name='savoirs_necessaires',
            field=models.TextField(blank=True, default='', verbose_name='Pour cela, je dois connaître'),
        ),
    ]
