# Generated by Django 6.0.3 on 2026-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fiche_portfolio_nouveaux_champs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfmp',
            name='nb_jours_prevus',
            field=models.PositiveIntegerField(blank=True, help_text='Durée totale de la PFMP en jours ouvrés', null=True, verbose_name='Nombre de jours prévus'),
        ),
    ]
