# Generated by Django 6.0.3 on 2026-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_renommer_referentiel_2btp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcm',
            name='classe',
        ),
        migrations.AddField(
            model_name='qcm',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='qcms', to='core.classe'),
        ),
    ]
