# Generated by Django 6.0.3 on 2026-10-03 08:16

import django.db.models.deletion
from django.db import migrations, models


def copier_diplomes_existants(apps, schema_editor):
    ProfilUtilisateur = apps.get_model('core', 'ProfilUtilisateur')
    DiplomeEleve = apps.get_model('core', 'DiplomeEleve')

    for profil in ProfilUtilisateur.objects.filter(
        est_sorti=True,
        type_diplome_obtenu__in=['cap', 'bac_pro'],
    ).select_related('classe'):
        annee = profil.annee_scolaire_sortie or 'Ancienne donnée'
        DiplomeEleve.objects.get_or_create(
            eleve_id=profil.pk,
            diplome=profil.type_diplome_obtenu,
            annee_scolaire=annee,
            defaults={
                'mention': profil.mention_obtenue or '',
                'classe': profil.classe.nom if profil.classe else '',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_qcm_classe_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomeEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(choices=[('cap', 'CAP'), ('bac_pro', 'Bac Pro')], max_length=20, verbose_name='Diplôme')),
                ('mention', models.CharField(blank=True, choices=[('', 'Sans mention'), ('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien')], default='', max_length=2, verbose_name='Mention')),
                ('annee_scolaire', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('classe', models.CharField(blank=True, max_length=100, verbose_name='Classe au moment de l’obtention')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes_obtenus', to='core.profilutilisateur', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Diplôme obtenu',
                'verbose_name_plural': 'Diplômes obtenus',
                'ordering': ['-annee_scolaire', 'diplome', 'eleve__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('eleve', 'diplome', 'annee_scolaire'), name='unique_diplome_eleve_annee')],
            },
        ),
        migrations.RunPython(copier_diplomes_existants, migrations.RunPython.noop),
    ]
