# Generated by Django 6.0.3 on 2026-10-03 08:47

from django.db import migrations, models


def renseigner_classe_historique(apps, schema_editor):
    SuiviPFMP = apps.get_model('core', 'SuiviPFMP')
    for suivi in SuiviPFMP.objects.select_related('eleve__classe').iterator():
        if suivi.eleve.classe_id:
            suivi.classe_au_moment = suivi.eleve.classe.nom
            suivi.save(update_fields=['classe_au_moment'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_diplomeeleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivipfmp',
            name='classe_au_moment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Classe au moment du PFMP'),
        ),
        migrations.RunPython(renseigner_classe_historique, migrations.RunPython.noop),
    ]
