# Generated by Django 6.0.3 on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_theme_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='epingle',
            field=models.BooleanField(default=False, verbose_name='Épinglé'),
        ),
    ]
