# Generated by Django 6.0.3 on 2026-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_theme_epingle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-epingle', 'ordre', 'nom'], 'verbose_name': 'Thème', 'verbose_name_plural': 'Thèmes'},
        ),
        migrations.AddField(
            model_name='dossier',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='dossiers_visibles', to='core.classe'),
        ),
    ]
