# Generated by Django 6.0.3 on 2026-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_copy_theme_classes_to_dossiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionqcm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qcm_images/'),
        ),
    ]
