"""
Django settings for plateforme project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()  # Charge automatiquement .env à la racine du projet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '7eSBcMNOnQlXa3iZQ9az-CKw7PzdCTMmLlRVmyMf7U7JC_AIddbQfqNJ9fIvEdY_Fz4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',  # django-storages (R2/S3)
    'core',
    'plateforme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Fichiers statiques en production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'plateforme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plateforme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# En production : variable DATABASE_URL fournie par Neon.tech
# En local : fallback sur SQLite
_DATABASE_URL = os.environ.get('DATABASE_URL', '')
if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# WhiteNoise sert les fichiers statiques directement depuis Render
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'    # collectstatic en prod
STATICFILES_DIRS = [BASE_DIR / 'static']  # dossier de dev (tes assets)


# ---------------------------------------------------------------------------
# Stockage des fichiers media
# En production (USE_S3=True) : Cloudflare R2 via django-storages/boto3
# En local (USE_S3=False)     : dossier media/ classique
# ---------------------------------------------------------------------------
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

if USE_S3:
    # --- Credentials Cloudflare R2 ---
    AWS_ACCESS_KEY_ID     = os.environ.get('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME')
    # URL d'API Cloudflare R2 : https://<account_id>.r2.cloudflarestorage.com
    AWS_S3_ENDPOINT_URL   = os.environ.get('R2_ENDPOINT_URL')
    AWS_S3_REGION_NAME    = 'auto'
    AWS_DEFAULT_ACL       = 'public-read'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH  = False  # URLs publiques sans signature

    # URL publique du bucket (R2.dev ou domaine custom Cloudflare)
    # Exemple : https://pub-xxxxx.r2.dev  ou  https://media.monsite.fr
    MEDIA_URL = os.environ.get('R2_PUBLIC_URL', '/media/') + '/'

    # Django 4.2+ : dictionnaire STORAGES unifié
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    # Développement local
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Auth redirects (login/logout) - CORRIGÉ
LOGIN_URL = 'core:login_prof'
LOGIN_REDIRECT_URL = 'core:dashboard_professeur'
LOGOUT_REDIRECT_URL = 'core:home'

# IA — Gemini
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
# Rotation automatique quand le quota d'une clé est épuisé
# Détection automatique de toutes les clés numérotées dans .env
# Ajouter simplement GEMINI_API_KEY_3, KEY_4... dans .env sans toucher au code
def _charger_cles(prefixe):
    cles = []
    cle1 = os.environ.get(prefixe, '')
    if cle1: cles.append(cle1)
    i = 2
    while True:
        cle = os.environ.get(f'{prefixe}_{i}', '')
        if not cle: break
        cles.append(cle)
        i += 1
    return cles

GEMINI_API_KEYS    = _charger_cles('GEMINI_API_KEY')
ELEVENLABS_API_KEYS = _charger_cles('ELEVENLABS_API_KEY')
