"""
Django settings for plateforme project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()  # Charge automatiquement .env à la racine du projet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '7eSBcMNOnQlXa3iZQ9az-CKw7PzdCTMmLlRVmyMf7U7JC_AIddbQfqNJ9fIvEdY_Fz4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS += ['.pythonanywhere.com']
ALLOWED_HOSTS += ['.onrender.com']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Ajoute ici le domaine exact de ton compte PythonAnywhere
_pa_host = os.environ.get('PYTHONANYWHERE_HOST', '')
CSRF_TRUSTED_ORIGINS = [
    'https://plateforme-pedagogique.onrender.com',
    f'https://{_pa_host}' if _pa_host else '',
]
CSRF_TRUSTED_ORIGINS = [x for x in CSRF_TRUSTED_ORIGINS if x]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'core',
    'plateforme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Fichiers statiques en production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'plateforme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plateforme.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# En production : variable DATABASE_URL fournie par Supabase
# En local : SQLite si DATABASE_URL absent du .env
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# WhiteNoise sert les fichiers statiques directement depuis Render
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'    # collectstatic en prod
STATICFILES_DIRS = [BASE_DIR / 'static']  # dossier de dev (tes assets)


# ---------------------------------------------------------------------------
# Stockage des fichiers media
# En production (USE_CLOUDINARY=True) : Cloudinary
# En local (USE_CLOUDINARY=False)     : dossier media/ classique
# ---------------------------------------------------------------------------
USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', 'False') == 'True'

if USE_CLOUDINARY:
    import cloudinary
    cloudinary.config(
        cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME'),
        api_key    = os.environ.get('CLOUDINARY_API_KEY'),
        api_secret = os.environ.get('CLOUDINARY_API_SECRET'),
        secure     = True,
    )
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'  # Cloudinary gère les URLs directement
else:
    # Développement local
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Cloudinary config (chargée même hors USE_CLOUDINARY pour éviter les erreurs d'import)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY':    os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# Auth redirects (login/logout) - CORRIGÉ
LOGIN_URL = 'core:login_prof'
LOGIN_REDIRECT_URL = 'core:dashboard_professeur'
LOGOUT_REDIRECT_URL = 'core:home'

# ---------------------------------------------------------------------------
# Sécurité HTTPS — actif uniquement en production (DEBUG=False)
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = False                  # Force HTTPS
    SECURE_HSTS_SECONDS = 31536000              # HSTS 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True                # Cookie session HTTPS uniquement
    CSRF_COOKIE_SECURE = True                   # Cookie CSRF HTTPS uniquement
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True

# IA — Gemini
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
# Rotation automatique quand le quota d'une clé est épuisé
# Détection automatique de toutes les clés numérotées dans .env
# Ajouter simplement GEMINI_API_KEY_3, KEY_4... dans .env sans toucher au code
def _charger_cles(prefixe):
    cles = []
    cle1 = os.environ.get(prefixe, '')
    if cle1: cles.append(cle1)
    i = 2
    while True:
        cle = os.environ.get(f'{prefixe}_{i}', '')
        if not cle: break
        cles.append(cle)
        i += 1
    return cles

GEMINI_API_KEYS    = _charger_cles('GEMINI_API_KEY')
ELEVENLABS_API_KEYS = _charger_cles('ELEVENLABS_API_KEY')
