"""
Django settings for plateforme project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# ===================================================================
# CHEMINS
# ===================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ===================================================================
# SÉCURITÉ
# ===================================================================
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    '7eSBcMNOnQlXa3iZQ9az-CKw7PzdCTMmLlRVmyMf7U7JC_AIddbQfqNJ9fIvEdY_Fz4'
)

DEBUG  = True

# ===================================================================
# HOSTS
# ===================================================================
ALLOWED_HOSTS = [
    'plateforme-pedagogique.onrender.com',
    '.onrender.com',
    'localhost',
    '127.0.0.1',
]

# ===================================================================
# CSRF — INDISPENSABLE POUR QUE LE LOGIN FONCTIONNE
# ===================================================================
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

_pa_host = os.environ.get('PYTHONANYWHERE_HOST', '')
CSRF_TRUSTED_ORIGINS = [
    'https://plateforme-pedagogique.onrender.com',
]
if _pa_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_pa_host}')

# ===================================================================
# APPLICATIONS
# ===================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'core',
    'plateforme',
]

# ===================================================================
# MIDDLEWARE
# ===================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ===================================================================
# URLS & WSGI
# ===================================================================
ROOT_URLCONF = 'plateforme.urls'
WSGI_APPLICATION = 'plateforme.wsgi.application'

# ===================================================================
# TEMPLATES
# ===================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ===================================================================
# BASE DE DONNÉES
# ===================================================================
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # ── Production : Supabase (PostgreSQL) ──
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,           # ← OBLIGATOIRE pour Supabase
        )
    }
else:
    # ── Développement local : SQLite ──
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ===================================================================
# VALIDATION MOT DE PASSE
# ===================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ===================================================================
# INTERNATIONALISATION
# ===================================================================
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

# ===================================================================
# FICHIERS STATIQUES
# ===================================================================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [BASE_DIR / 'static']

# ===================================================================
# FICHIERS MEDIA — Cloudinary en prod, local en dev
# ===================================================================
USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', 'False') == 'True'

if USE_CLOUDINARY:
    import cloudinary
    cloudinary.config(
        cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
        api_key=os.environ.get('CLOUDINARY_API_KEY'),
        api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
        secure=True,
    )
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# ===================================================================
# AUTHENTIFICATION — Redirections
# ===================================================================
LOGIN_URL = 'core:login_prof'
LOGIN_REDIRECT_URL = 'core:dashboard_professeur'
LOGOUT_REDIRECT_URL = 'core:home'

# ===================================================================
# CRÉATION AUTO DU SUPERUSER (pour Render sans Shell)
# ===================================================================
DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', '')
DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL', '')
DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD', '')

# ===================================================================
# SÉCURITÉ HTTPS — Production uniquement
# ===================================================================
if not DEBUG:
    SECURE_SSL_REDIRECT = False          # Render gère le HTTPS lui-même
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_CONTENT_TYPE_NOSNIFF = True

# ===================================================================
# IA — Gemini & ElevenLabs
# ===================================================================
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')


def _charger_cles(prefixe):
    cles = []
    cle1 = os.environ.get(prefixe, '')
    if cle1:
        cles.append(cle1)
    i = 2
    while True:
        cle = os.environ.get(f'{prefixe}_{i}', '')
        if not cle:
            break
        cles.append(cle)
        i += 1
    return cles


GEMINI_API_KEYS = _charger_cles('GEMINI_API_KEY')
ELEVENLABS_API_KEYS = _charger_cles('ELEVENLABS_API_KEY')